version: 2

updates:
  - package-ecosystem: npm
    directories:
      - "**/*"
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(deps)"
    groups:
      patch:
        applies-to: version-updates
        update-types:
          - patch
          - minor

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(deps)"
    groups:
      github-actions:
        patterns:
          - "*"
