packages:
  - "packages/*"


# Require packages to be at least 7 days old before being allowed to be installed
minimumReleaseAge: 10080

overrides:
  proxy-addr: ^2.0.8
  shell-quote: ^1.11.0

allowBuilds:
  "@apollo/protobufjs": true
  esbuild: true
  protobufjs: true
