name: Release
on: [push]

env:
  CI: true

jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Set up Node.js
        uses: labd/gh-actions-typescript/pnpm-install@e7a21fb56b52bf2d91616e34f0bc3f4f9a821b62 # main

      - name: Lint
        run: pnpm lint

  build:
    name: Build, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        node: ["22.x", "24.x", "26.x"]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Set up Node.js
        uses: labd/gh-actions-typescript/pnpm-install@e7a21fb56b52bf2d91616e34f0bc3f4f9a821b62 # main
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm run test:ci

  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: release
    needs: build
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: labd/gh-actions-typescript/pnpm-install@e7a21fb56b52bf2d91616e34f0bc3f4f9a821b62 # main

      - name: Run build
        run: pnpm build

      - name: Upgrade npm for trusted publishing
        run: npm i -g npm@^11.6.4

      - name: Create and publish versions
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          title: "Release new version"
          commit: "update version"
          publish: pnpm publish:ci
          version: pnpm publish:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
